#!/bin/bash
(( $# < 1 )) && { echo "usage: $0 majorversion [minorversion]"; exit 1; }

if [[ $2 ]]; then
  vc_osiso="${HOME}/Downloads/CentOS-${1}.${2}-x86_64-minimal.iso" # 6.7 sha256sum 9d3fec5897be6b3fed4d3dda80b8fa7bb62c616bbfd4bdcd27295ca9b764f498
  vc_basebox="vagrant-centos-${1}-${2}"
else
  vc_osiso="${HOME}/Downloads/CentOS-${1}-x86_64-Minimal.iso"
  vc_basebox="vagrant-centos-${1}"
fi
vc_guestiso="${HOME}/Downloads/VBoxGuestAdditions_5.0.12.iso" # sha256sum 61a19c9ec4b449cbc6bb41b636b03a16bf5a47ffa4943423d262863017e8bc9b
vc_vboxbase="${HOME}/VirtualBox VMs"
vc_basebox="vagrant-centos-${1}"
vc_hddbase="${vc_vboxbase}/${vc_basebox}/${vc_basebox}"
vc_hddfile="${vc_hddbase}.vdi"

checkdir() { [[ ! -d "$1" ]] && { echo "ERROR: missing $1 dir!"; exit 1; } }
checkiso() { [[ ! -e "$1" ]] && { echo "ERROR: missing $1 file!"; exit 1; } }

checkdir "$HOME"
checkdir "$vc_vboxbase"
checkiso "$vc_osiso"
checkiso "$vc_guestiso"

VBoxManage -v &> /dev/null || { echo "ERROR: VBoxManage not in path!"; exit 1; }

VBoxManage createvm --name "$vc_basebox" --register
VBoxManage modifyvm "$vc_basebox" --ostype RedHat_64 --memory 512 --vram 16 --rtcuseutc on --ioapic on --largepages off --paravirtprovider legacy --boot1 disk --boot2 dvd --boot3 none --boot4 none --pae off --nic1 nat --nictype1 82540EM
VBoxManage storagectl "$vc_basebox" --name SATAController --add sata --portcount 1
VBoxManage createhd --filename "$vc_hddfile" --size 40960
VBoxManage storageattach "$vc_basebox" --storagectl SATAController --port 0 --type hdd --medium "$vc_hddfile"
VBoxManage storagectl "$vc_basebox" --name IDEController --add ide
VBoxManage storageattach "$vc_basebox" --storagectl IDEController --device 0 --port 0 --type dvddrive --medium "$vc_osiso"
VBoxManage storageattach "$vc_basebox" --storagectl IDEController --device 0 --port 1 --type dvddrive --medium "$vc_guestiso"
VBoxManage startvm "$vc_basebox"

ruby -rsocket -e 'puts "Kickstart URL: ks=http://" + Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address + ":8000/vagrant-centos-MAJORVERSION.ks"'
ruby -rwebrick -e 's=WEBrick::HTTPServer.new(:Port=>8000,:DocumentRoot=>".");trap("INT") { s.shutdown }; s.start'

VBoxManage modifyvm "$vc_basebox" --boot2 none
VBoxManage storagectl "$vc_basebox" --name IDEController --remove

vagrant package --base "$vc_basebox" --output "${vc_basebox}.box"

VBoxManage unregistervm "$vc_basebox" --delete
